FROM imply/imply:2.8.7 AS imply

COPY ./data/ /tmp/data/
COPY ./docker/druid_ingest_data.py /opt/imply-2.8.7/bin/druid_ingest_data.py
COPY ./docker/entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]