FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /app

WORKDIR /solution
COPY ./BigBank.sln ./
COPY ./src/BigBank.OLAP/BigBank.OLAP.csproj ./src/BigBank.OLAP/BigBank.OLAP.csproj
COPY ./src/BigBank.WebApi/BigBank.WebApi.csproj ./src/BigBank.WebApi/BigBank.WebApi.csproj
COPY ./tests/BigBank.UnitTests/BigBank.UnitTests.csproj ./tests/BigBank.UnitTests/BigBank.UnitTests.csproj
COPY ./tests/BigBank.IntegrationTests/BigBank.IntegrationTests.csproj ./tests/BigBank.IntegrationTests/BigBank.IntegrationTests.csproj

RUN dotnet restore

COPY . ./

WORKDIR ./src/BigBank.WebApi
FROM build AS publish
RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/core/aspnet:2.1
WORKDIR /app
COPY --from=publish /app .

ENTRYPOINT ["dotnet", "BigBank.WebApi.dll"]